### ISSUE TITLE
forgive.jpg 的英文错了……

### ISSUE THREAD

**Issue by kemingy** [hui-z/ForgiveDB#11]
图片上的英文

frogive -> forgive

**Comment by liriansu-opus** [comment]
~~expected behavior, wont fix~~ ~~+1s~~
尴尬，就你老实地提出来了。

既然这样，就让我们给这个Issue加个~~精华~~Label吧

**Comment by tothegump** [comment]
给大佬递英语书

**Comment by ice1000** [comment]
万一是为了表达表情的作者的口音呢。我觉得可以close。
